# Generated by Django 5.1.2 on 2024-10-30 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.TextField(max_length=60)),
                ('Marca', models.TextField(max_length=60)),
                ('Modelo', models.TextField(max_length=60)),
                ('Serial', models.TextField(max_length=60)),
                ('Area', models.TextField(max_length=60)),
                ('Responsable', models.TextField(max_length=60)),
            ],
        ),
    ]
