# Generated by Django 5.1.2 on 2024-10-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Marca',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Responsable',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Serial',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='Área',
            field=models.CharField(max_length=100),
        ),
    ]
