# Generated by Django 5.1.2 on 2024-10-31 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.TextField(max_length=30)),
                ('nombre', models.TextField(max_length=100)),
                ('apellido', models.TextField(max_length=100)),
                ('correo', models.TextField(max_length=100)),
            ],
        ),
    ]
