# Generated by Django 5.1.2 on 2024-11-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce', '0002_responsable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Area',
            field=models.TextField(default='Default Area', max_length=60),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='apellido',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='responsable',
            name='nombre',
            field=models.TextField(max_length=60),
        ),
    ]
