# Generated by Django 5.1.2 on 2024-11-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hce', '0003_alter_equipo_area_alter_responsable_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='Responsable',
            field=models.IntegerField(),
        ),
    ]
