# Generated by Django 5.1.2 on 2024-11-04 19:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hce", "0004_alter_equipo_responsable"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipo",
            name="imagen",
            field=models.ImageField(null=True, upload_to="imagenes/"),
        ),
    ]
